kind: pipeline
name: default
steps:
  # - name: initial_notification
  #   image: plugins/slack
  #   settings:
  #     webhook:
  #       from_secret: slack_webhook
  #     template: >
  #       There is a new deploy in process for *{{repo.name}}* 

  #       Author: *{{build.author}}*. Branch: *{{build.branch}}*. Event: *{{build.event}}*. 

  #       Logs: {{build.link}}

  - name: initial_notification_vshn
    image: mike1pol/drone-rocket
    settings:
      url:
        from_secret: rocket_url
      user_id:
        from_secret: rocket_user
      token:
        from_secret: rocket_token
      channel:
        from_secret: rocket_channel
      message: >
        There is a new deploy in process for *{{repo.name}}* 
        Logs: {{build.link}}

  - name: get-cache
    image: meltwater/drone-cache:dev
    settings:
      restore: true
      endpoint: minio.minio:9000
      bucket: vshn-website
      region: eu-west-1
      path_style: true
      cache_key: '{{.Repo.Name}}-{{ .Commit.Branch }}-{{ checksum "package.json" }}'
      mount:
        - "node_modules"
        - ".cache"
        - "public"
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    depends_on:
      - initial_notification

  - name: build
    image: node:14.13.1-slim
    environment:
      WP_GRAPHQL_URL: https://vshn.cyon.site/graphql
      GATSBY_DEFAULT_SITE_URL: https://www.vshn.ch/
      GATSBY_CONCURRENT_DOWNLOAD: 5
      WP_HTACCESS_USERNAME: vshn
      WP_HTACCESS_PASSWORD:
        from_secret: wp_htaccess_password
    commands:
      - npm install --prefer-offline --no-audit
      - |
        [ -n "$CACHE_CLEAN" ] && npm run clean
      - npm run build
    depends_on:
      - get-cache

  - name: update-cache
    image: meltwater/drone-cache:dev
    settings:
      rebuild: true
      endpoint: minio.minio:9000
      bucket: vshn-website
      region: eu-west-1
      path_style: true
      cache_key: '{{.Repo.Name}}-{{ .Commit.Branch }}-{{ checksum "package.json" }}'
      mount:
        - "node_modules"
        - ".cache"
        - "public"
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    depends_on:
      - build

  - name: netlify-deploy-preview
    image: williamjackson/netlify-cli
    environment:
      NETLIFY_SITE_ID: cbeefaa7-9e70-4cf1-b568-accbfb877fba
      NETLIFY_AUTH_TOKEN:
        from_secret: netlify_access_token
    commands:
      - netlify deploy --dir=public --alias=$DRONE_COMMIT_BRANCH
    depends_on:
      - build
    when:
      branch:
        exclude:
          - master

  - name: netlify-success-notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template: >
        Successful deploy of {{repo.name}}

        Deploy preview URL: https://{{build.branch}}--vshn.netlify.app
    when:
      branch:
        exclude:
          - master
    depends_on:
      - netlify-deploy-preview

  - name: netlify-success-notification-vshn
    image: mike1pol/drone-rocket
    settings:
      url:
        from_secret: rocket_url
      user_id:
        from_secret: rocket_user
      token:
        from_secret: rocket_token
      channel:
        from_secret: rocket_channel
      message: >
        Successful deploy of {{repo.name}}

        Deploy preview URL: https://{{build.branch}}--vshn.netlify.app
    when:
      branch:
        exclude:
          - master
    depends_on:
      - netlify-deploy-preview

  - name: netlify-deploy
    image: williamjackson/netlify-cli
    environment:
      NETLIFY_SITE_ID: cbeefaa7-9e70-4cf1-b568-accbfb877fba
      NETLIFY_AUTH_TOKEN:
        from_secret: netlify_access_token
    commands:
      - netlify deploy --prod --dir=public
    depends_on:
      - build
    when:
      branch:
        - master

  - name: netlify-success-notification-prod
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template: >
        Successful deploy of {{repo.name}}

        Deploy URL: https://vshn.netlify.app
    when:
      branch:
        - master
    depends_on:
      - netlify-deploy

  - name: netlify-success-notification-prod-vshn
    image: mike1pol/drone-rocket
    settings:
      url:
        from_secret: rocket_url
      user_id:
        from_secret: rocket_user
      token:
        from_secret: rocket_token
      channel:
        from_secret: rocket_channel
      message: >
        Successful deploy of {{repo.name}}

        Deploy URL: https://vshn.netlify.app
    when:
      branch:
        - master
    depends_on:
      - netlify-deploy

  - name: build-gatsby-preview-docker
    image: plugins/docker
    settings:
      repo: registry.pixelpoint.io/vshn-website
      registry: registry.pixelpoint.io
      dockerfile: Dockerfile.preview
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        exclude:
          - custom
    depends_on:
      - build

  - name: deploy-gatsby-preview-server
    image: peloton/drone-k8s-deployment
    settings:
      insecure: false
      deployment_names: vshn-website
      container_names: vshn-website
      namespaces: websites
      docker_image: registry.pixelpoint.io/vshn-website:latest
      date_label: deployment.drone.io/date-deployed
      url:
        from_secret: kubernetes_url
      token:
        from_secret: kubernetes_token
    when:
      branch:
        - master
      event:
        exclude:
          - custom
    depends_on:
      - build-gatsby-preview-docker

  - name: failed_status_notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template: >
        Deploy did not complete for *{{repo.name}}*. 

        Author: *{{build.author}}*. Branch: *{{build.branch}}*. Event: *{{build.event}}*. 

        Logs: {{build.link}}
    depends_on:
      - deploy-gatsby-preview-server
      - netlify-deploy-preview
    when:
      status:
        - failure

  - name: failed_status_notification_vshn
    image: mike1pol/drone-rocket
    settings:
      url:
        from_secret: rocket_url
      user_id:
        from_secret: rocket_user
      token:
        from_secret: rocket_token
      channel:
        from_secret: rocket_channel
      message: >
        Deploy did not complete for *{{repo.name}}*. 

        Author: *{{build.author}}*. Branch: *{{build.branch}}*. Event: *{{build.event}}*. 

        Logs: {{build.link}}
    depends_on:
      - deploy-gatsby-preview-server
      - netlify-deploy-preview
    when:
      status:
        - failure

trigger:
  event:
    - push
    - custom
