kind: pipeline
name: default
steps:
  #   - name: initial_notification_vshn
  #     image: mike1pol/drone-rocket
  #     settings:
  #       url:
  #         from_secret: rocket_url
  #       user_id:
  #         from_secret: rocket_user
  #       token:
  #         from_secret: rocket_token
  #       channel:
  #         from_secret: rocket_channel
  #       message: >
  #         There is a new deploy in process for *{{repo.name}}*
  #         Logs: {{build.link}}

  # - name: get-cache
  #   image: meltwater/drone-cache:dev
  #   settings:
  #     restore: true
  #     endpoint: minio-api.main:9000
  #     bucket: vshn-website
  #     region: eu-west-1
  #     path_style: true
  #     cache_key: '{{.Repo.Name}}-{{ .Commit.Branch }}-{{ checksum "package.json" }}'
  #     mount:
  #       - "node_modules"
  #       - ".cache"
  #       - "public"
  #   environment:
  #     AWS_ACCESS_KEY_ID:
  #       from_secret: minio_access_key
  #     AWS_SECRET_ACCESS_KEY:
  #       from_secret: minio_secret_key

  - name: build
    image: lnikell/node-gatsby:16.14.1-alpine
    environment:
      WP_GRAPHQL_URL: https://vshn.cyon.site/graphql
      GATSBY_DEFAULT_SITE_URL: https://www.vshn.ch/
      GATSBY_CONCURRENT_DOWNLOAD: 5
      WP_HTACCESS_USERNAME: vshn
      WP_HTACCESS_PASSWORD:
        from_secret: wp_htaccess_password
    commands:
      - npm install --platform=linux --arch=x64 sharp
      - npm ci --ignore-scripts
      - |
        [ -n "$CACHE_CLEAN" ] && npm run clean
      - npm run build

  - name: update-cache
    image: meltwater/drone-cache:dev
    settings:
      rebuild: true
      endpoint: minio-api.main:9000
      bucket: vshn-website
      region: eu-west-1
      path_style: true
      cache_key: '{{.Repo.Name}}-{{ .Commit.Branch }}-{{ checksum "package.json" }}'
      mount:
        - "node_modules"
        - ".cache"
        - "public"
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_key
    depends_on:
      - build

  - name: netlify-deploy-preview
    image: williamjackson/netlify-cli:8.6.0
    environment:
      NETLIFY_SITE_ID: cbeefaa7-9e70-4cf1-b568-accbfb877fba
      NETLIFY_AUTH_TOKEN:
        from_secret: netlify_access_token
    commands:
      - netlify deploy --dir=public --alias=$DRONE_COMMIT_BRANCH
    depends_on:
      - build
    when:
      branch:
        exclude:
          - master

  #   - name: netlify-success-notification-vshn
  #     image: mike1pol/drone-rocket
  #     settings:
  #       url:
  #         from_secret: rocket_url
  #       user_id:
  #         from_secret: rocket_user
  #       token:
  #         from_secret: rocket_token
  #       channel:
  #         from_secret: rocket_channel
  #       message: >
  #         Successful deploy of {{repo.name}}

  #         Deploy preview URL: https://{{build.branch}}--vshn.netlify.app
  #     when:
  #       branch:
  #         exclude:
  #           - master
  #     depends_on:
  #       - netlify-deploy-preview

  - name: netlify-deploy
    image: williamjackson/netlify-cli:8.6.0
    environment:
      NETLIFY_SITE_ID: cbeefaa7-9e70-4cf1-b568-accbfb877fba
      NETLIFY_AUTH_TOKEN:
        from_secret: netlify_access_token
    commands:
      - netlify deploy --prod --dir=public
    depends_on:
      - build
    when:
      branch:
        - master

  #   - name: netlify-success-notification-prod-vshn
  #     image: mike1pol/drone-rocket
  #     settings:
  #       url:
  #         from_secret: rocket_url
  #       user_id:
  #         from_secret: rocket_user
  #       token:
  #         from_secret: rocket_token
  #       channel:
  #         from_secret: rocket_channel
  #       message: >
  #         Successful deploy of {{repo.name}}

  #         Deploy URL: https://vshn.netlify.app
  #     when:
  #       branch:
  #         - master
  #     depends_on:
  #       - netlify-deploy

#   - name: failed_status_notification_vshn
#     image: mike1pol/drone-rocket
#     settings:
#       url:
#         from_secret: rocket_url
#       user_id:
#         from_secret: rocket_user
#       token:
#         from_secret: rocket_token
#       channel:
#         from_secret: rocket_channel
#       message: >
#         Deploy did not complete for *{{repo.name}}*.

#         Author: *{{build.author}}*. Branch: *{{build.branch}}*. Event: *{{build.event}}*.

#         Logs: {{build.link}}
#     depends_on:
#       - deploy-gatsby-preview-server
#       - netlify-deploy-preview
#     when:
#       status:
#         - failure

trigger:
  event:
    - push
    - custom
