# Check out https://hub.docker.com/r/pixelpointltd/gatsby-docker to select a new base image
FROM node:16.14.0-slim

# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

# Bundle app source code
COPY --chown=node . .

CMD [ "npm", "start"]