name: Generate dummy activity so cron jobs stay active
on:
  workflow_dispatch:
  schedule:
  - cron: '45 0 * * *'
jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: make a dummy commit every 50 days to prevent the cronjob to be disabled after 60 days of inactivity
        uses: gautamkrishnar/keepalive-workflow@v1
