name: Clear gatsby cloud build cache

on:
  workflow_dispatch:

jobs:
  clear:
    runs-on: ubuntu-latest

    steps:
      - name: Webhook Action
        uses: joelwmale/webhook-action@2.3.2
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"x-gatsby-cache": "false"}'
          body: ''
