name: Clear gatsby cloud build cache
on:
  workflow_dispatch:
  schedule:
  # hourly on weekdays
  - cron: '55 3-20 * * 1-5'
jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook Action
        run: 'curl -X POST ${{ secrets.WEBHOOK_URL }} --header "x-gatsby-cache: false"'
